# Generated by Django 2.1.1 on 2018-11-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('contacts', models.CharField(db_index=True, max_length=50, verbose_name='Контакты')),
                ('author', models.CharField(db_index=True, max_length=50, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('price', models.FloatField(db_index=True, verbose_name='Цена, руб.')),
                ('image', models.ImageField(upload_to='goods/list', verbose_name='Основное изображение')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/detail', verbose_name='Дополнительное изображение')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
            ],
            options={
                'verbose_name': 'изображение к товару',
                'verbose_name_plural': 'изображения к товару',
            },
        ),
    ]
